#!/bin/sh
#
# Startup / shutdown script for the fae server
#
# Copyright (c) 2011, FunPlus, Inc.
# All rights reserved
#
#
### BEGIN INIT INFO
# Provides:          faed
# Required-Start:    $network $local_fs
# Required-Stop:
# Should-Start:      $named
# Should-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    fae server
# Description:          fae server

### END INIT INFO

. /etc/init.d/functions

if [ "$(id -u)" != "0" ]; then
    echo "Must run as root"
    exit 1
fi

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

FAE_HOME=/sgn/app/fae
DAEMON=$FAE_HOME/bin/faed
PIDFILE=$FAE_HOME/var/faed.pid
CONFIGFILE=$FAE_HOME/etc/faed.cf
LOGFILE=$FAE_HOME/var/faed.log
LOCKFILE=$FAE_HOME/var/faed.lock

test -f $DAEMON || exit 0
test -f $CONFIGFILE || exit 0

# Otherwise, RHEL (and apparently Fedora) tries to "help" and set soft
# limit of core file size to 0 for daemons. It's done as part of
# daemon shell function shortly after changing user. See MB-6601
DAEMON_COREFILE_LIMIT=unlimited

start() {
    touch $PIDFILE 
    chown fae $PIDFILE 
    cd $FAE_HOME
    ulimit -n 40960
    ulimit -c unlimited
    ulimit -l unlimited
    daemon --pidfile PIDFILE "/usr/sbin/daemonize $DAEMON -conf $CONFIGFILE -level trace -log $LOGFILE -lockfile $LOCKFILE"
    errcode=$?
    return $errcode
}

stop() {
    daemon "$DAEMON -k -lockfile $LOCKFILE"
    errcode=$?
    return $errcode
}

running() {
    pidofproc -p $PIDFILE $DAEMON >/dev/null
    errcode=$?
    return $errcode
}

case $1 in
    start)
        if running ; then
            warning && echo "fae-server is already started"
            exit 0
        fi
        echo -n $"Starting fae-server"
        start
        echo
        ;;
    stop)
        echo -n $"Stopping fae-server"
        stop
        echo
        ;;
    restart)
        echo -n $"Stopping fae-server"
        stop
        echo
        echo -n $"Starting fae-server"
        start
        echo
        ;;
    status)
        if running ; then
            echo "fae-server is running"
            exit 0
        else
            echo "fae-server is not running"
            exit 3
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/faed {start|stop|restart|status}" >&2
        exit 3
esac
