namespace go  fun.rpc
namespace php fun.rpc

/**
 * Thrift don't support service multiplex, so we have to bury all
 * services into the giant FunServant.
 *
 * We don't want to use different port for different service for 
 * multiplex of service, that will lead to complexity for client.
 */
service FunServant {
    /**
     * @return string - always 'pong'
     */
    string ping(),

    //=================
    // memcache section
    //=================

    /**
     * Set
     *
     * @param string key -
     * @param binary value -
     * @param i32 expiration - in seconds: either a relative time from now (up to 1 month), or 
     *     an absolute Unix epoch time. Zero means the Item has no expiration time.
     */
    bool mc_set(1: string key, 2: binary value, 3: i32 expiration),

    /**
     * Get
     */
    binary mc_get(1: string key),

    /**
     * Write a dlog event.
     *
     * timestamp will be generated by servant.
     *
     * @param string area
     * @param string json Client is responsible to jsonize
     */
    oneway void dlog(1: string area, 2: string json),
}
